version: "3.8"
services:
  nginx:
    image: nginx-compose
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./style.css:/usr/share/nginx/html/style.css
      - ./app.js:/usr/share/nginx/html/app.js
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./nginx.key:/etc/nginx/ssl/nginx.key
